version: '2'

services:

  python_elk:
    build:
      context: python/
    ports:
      - "5081:5080"

  nodejs_elk:
    build:
      context: nodejs/
    ports:
      - "3001:3000"

  java_elk:
    build:
      context: java/
    ports:
      - "8081:8080"

networks:
  default:
    external:
      name: dockerelk_elk
